services:
  coda-ufficio:
    container_name: coda-ufficio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2323:2323"
    environment:
      PORT: "2323"
      HOST: "0.0.0.0"
      NODE_ENV: "production"
    restart: unless-stopped

